package corba;


/**
* corba/InterfazAccesoArduinoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Luis/workspace-MARS/prj-ServidorCORBA-AccesoArduino/InterfazAccesoArduino.idl
* sábado 8 de abril de 2017 00H51' CEST
*/

public abstract class InterfazAccesoArduinoPOA extends org.omg.PortableServer.Servant
 implements corba.InterfazAccesoArduinoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("enviarOrdenArduino", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/InterfazAccesoArduino/enviarOrdenArduino
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.enviarOrdenArduino (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/InterfazAccesoArduino:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public InterfazAccesoArduino _this() 
  {
    return InterfazAccesoArduinoHelper.narrow(
    super._this_object());
  }

  public InterfazAccesoArduino _this(org.omg.CORBA.ORB orb) 
  {
    return InterfazAccesoArduinoHelper.narrow(
    super._this_object(orb));
  }


} // class InterfazAccesoArduinoPOA
