package corba;


/**
* corba/InterfazAccesoArduino.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Luis/workspace-MARS/prj-ServidorCORBA-AccesoArduino/InterfazAccesoArduino.idl
* sábado 8 de abril de 2017 00H51' CEST
*/

public interface InterfazAccesoArduino extends InterfazAccesoArduinoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterfazAccesoArduino
