package corba;

/**
* corba/InterfazAccesoArduinoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Luis/workspace-MARS/prj-ServidorCORBA-AccesoArduino/InterfazAccesoArduino.idl
* sábado 8 de abril de 2017 00H51' CEST
*/

public final class InterfazAccesoArduinoHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.InterfazAccesoArduino value = null;

  public InterfazAccesoArduinoHolder ()
  {
  }

  public InterfazAccesoArduinoHolder (corba.InterfazAccesoArduino initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.InterfazAccesoArduinoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.InterfazAccesoArduinoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.InterfazAccesoArduinoHelper.type ();
  }

}
