package corba;


/**
* corba/InterfazAccesoArduinoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Luis/workspace-MARS/prj-ServidorCORBA-AccesoArduino/InterfazAccesoArduino.idl
* sábado 8 de abril de 2017 00H51' CEST
*/

public interface InterfazAccesoArduinoOperations 
{
  String enviarOrdenArduino (String msg);
} // interface InterfazAccesoArduinoOperations
